### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/CVBacklogUI#11]
How is this licensed?

**Comment by ghost** [comment]
I have no idea =oP Whatever you guys want.

**Comment by PeeHaa** [comment]
I would say MIT or something BSD like?

**Comment by gooh** [comment]
MIT (should also be added to the old backlog)

**Comment by rdlowrey** [comment]
MIT_all_of_the_things.jpg

**Comment by hakre** [comment]
> Whatever you guys want.

Thank you :) +1

**Comment by DaveRandom** [comment]
> Whatever you guys want.

Ahh, the WEYGW license. I believe it used to be called the "piss off with your incessant licensing and just let me write my damn code" license. I think new name is snappier.

**Comment by Ocramius** [comment]
MIT ftw!

**Comment by ghost** [comment]
MIT it is, license file will be there on my next commit.
