### ISSUE TITLE
Question Counter Show Count Of 1 When No Cache File Is Loaded

### ISSUE THREAD

**Issue by ghost** [Room-11/CVBacklogUI#13]
If there is no cache file to load there will be a soft error saying it is not available, but the error is put as a table cell on its own row. This is so the error will appear nicely if such an issue is encountered during auto-refresh. However, the JS counter code is counting that error row so the counter shows:

> Displaying 1 / 0

Maybe add a check to ignore the cell if the `.error-message` class is present?

**Comment by DaveRandom** [comment]
Fixed in https://github.com/PHP-Chat/CVBacklogUI/commit/9dfe0d4611d9790c8a629172097ca303cc71f85f
