### ISSUE TITLE
Counter Shows 'NaN' If No Cache Files Loaded

### ISSUE THREAD

**Issue by ghost** [Room-11/CVBacklogUI#14]
If no cache files are loaded the counter is `0 / 0`. However, if you manually check a checkbox, or it gets auto-checked through localStorage then the counter shows `Displaying NaN / 0`. It should avoid doing any of the counting if `tr.error-message` is present in the data table, which would indicate there was a problem getting data either on page load or AJAX refresh, which would always means 0 entries.

**Comment by ghost** [comment]
ping @DaveRandom if you have time can you look into this? If not, it's ok.  I can throw some things at the code and see if it does something =oP

**Comment by DaveRandom** [comment]
@KyraD I'll take a look at it ASAP, either later today or tomorrow

**Comment by ghost** [comment]
@DaveRandom pew! pew! pew!

**Comment by ghost** [comment]
fixed in v1.2 branch
