### ISSUE TITLE
Update Twitter Bootstrap CSS To 3.0

### ISSUE THREAD

**Issue by ghost** [Room-11/CVBacklogUI#16]
~~Ditch Twitter Bootstrap CSS framework and instead put all CSS into single LESS file. I'll get this done whenever I have time since low priority.~~

**UPDATE:**
Upgrade code so it is compatible with the latest Twitter Bootstrap CSS.

**Comment by morrisonlevi** [comment]
Why don't you use the Twitter Bootstrap LESS files? I'm not trying to promote it or anything, but you didn't give any justification so I thought I'd ask.

**Comment by ghost** [comment]
@morrisonlevi It's pretty bloated even when I remove the LESS files I don't need. The layout is fairly simple and should not really need to be dependent on a CSS framework. I like TB and all, but think we can do better without it in this instance.

Unless we plan on using TB for the main site, then it would make sense to keep it, but TB is pretty frowned upon just like jQuery since the bloat of all the unneeded code has no upside. I mean if you or anyone else do not want it's removal I'm fine with keeping it.

Do note that TB 3.0rc1 is out and if we do plan on using TB for main site it will be using that version which I have tested on the dev site and some things break. So the code will have to be fixed for that version. If that is the case I will just change this issue to "Update Twitter Bootstrap To 3.0" instead.

**Comment by ghost** [comment]
Updated to 3.0 in new Silex based development branch. Which will be posted to repo within a few weeks. Still got a lot more to do before upload it all.
