### ISSUE TITLE
Options Are Checked By Default When They Should Be Unchecked By Default

### ISSUE THREAD

**Issue by ghost** [Room-11/CVBacklogUI#7]
Right now the options are defaulting to checked state on page load if options are not saved to localStorage, which the localStorage then saves so subsequent requests are also checked. The HTML is not marked to check so issues lies somewhere in the JS code. I'm not the only one to report this http://chat.stackoverflow.com/transcript/message/10725312#10725312

**Comment by ghost** [comment]
@DaveRandom can you make it so that if I set the default to checked via the HTML for an option it won't clear it on page load?

**Comment by DaveRandom** [comment]
@KyraD Sorry I don't quite follow?

It now defaults to whatever is defined in the HTML ([`el.hasAttribute('checked')`](https://github.com/PHP-Chat/CVBacklogUI/commit/e7b6037ddaacedbf0724913057640530f981f961#L0R207)) but if there's a value in localStorage that value will be used over the default. All values are currently populated into localStorage on page load as the default - do you want them to only be stored if the value changes from the default?
