### ISSUE TITLE
Adjust scrolled list to viewport

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/CVBacklogUI#8]
Add some JS magic to adjust the height of the scrollable list to the view port.

**Comment by PeeHaa** [comment]
This means that there will be no vertical scrollbar and the entire contents (including the footer) will be visivle on the viewport.

Also don't forget about people resizing the window.

:+1:

**Comment by ghost** [comment]
Removed the scrolled option, and setup sticky header. You can view it live at http://dev.cv-pls.com/backlog this does not require any additional height resizing and is a much better option than before as it allows more questions to be visible and does not require any buggy table overflow stuff. Just took awhile to figure out how to nicely do it.

**Comment by morrisonlevi** [comment]
@KyraD The link is dead.

**Comment by ghost** [comment]
@morrisonlevi It's working for me both the main and dev sites load. Is it still not loading for you? Btw main site was synced.
