### ISSUE TITLE
Correct the status of migrated questions

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/CVBacklogUI#9]
Migrated questions are marked as locked

**Comment by ghost** [comment]
This looks related http://meta.stackoverflow.com/questions/147766/what-is-the-reason-for-locking-a-question-migrated-from-another-site-that-is-the

**Comment by ghost** [comment]
I'm going to drop migrated questions from the backlog since it does not matter what site it is migrated to or from, they can not be moderated due to the lock status. So for the time being we'll do that, unless SO changes this weird rule.

**Comment by ghost** [comment]
Better solution for now at least (next release).

I plan on marking questions migrated TO the site as a review question, and a marking questions migrated FROM the site as auto-delete _(will be deleted by system in 30 days)_
